export const CHANGE_TOP_PALYLIST ="CHANGE_TOP_PALYLIST";

export const CHANGE_HIGHQUALITY ="CHANGE_HIGHQUALITY";
export const CHANGE_TOP_ALBUM ="CHANGE_TOP_ALBUM";
export const CHANGE_All_PLAYLIST ="CHANGE_All_PLAYLIST";

export const CHANGE_RANKINGLIST ="CHANGE_RANKINGLIST";

export const CHANGE_ALLRANKINGLIST ="CHANGE_ALLRANKINGLIST";
export const CHANGE_ARTISTRANKINGLIST ="CHANGE_ARTISTRANKINGLIST";
export const CHANGE_RANKINGDETAIL ="CHANGE_RANKINGDETAIL";