export const CHANGE_SONG_LIST = "CHANGE_SONG_LIST";
export const CHANGE_SINGER_MV = "CHANGE_SINGER_MV";
export const CHANGE_SINGER_ALBUM = "CHANGE_SINGER_ALBUM";
export const CHANGE_SINGER_DESC = "CHANGE_SINGER_DESC"
